name: transactions_tracker
description: "A Flutter app to track user cards and transactions"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^3.0.1
  json_annotation: ^4.8.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  mockito: ^5.4.2
  json_serializable: ^6.7.1
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
